### PR TITLE
Add setLocation support

### PR DESCRIPTION
**Pull request by LeoNatan**
There is now new commands:

```
applesimutils --setLocation "[51.51915, -3.12907]"
```
or 
```
applesimutils --setLocation none
```

### CODE REVIEW

**Comment by noomorph** [comment]
💋

**Comment by noomorph** [comment]
Let me know when I can play with the new version via `brew install`

**Comment by d4vidi** [comment]
Thanks!!!

**Comment by alon-ha** [comment]
Thanks!

**Comment by LeoNatan** [comment]
Cheers

**Pull request merged**
