### PR TITLE
fix notifications permission on Xcode 9

### PR DESCRIPTION
**Pull request by erezrokah**
After fiddling with the location permission I've noticed the notifications permission doesn't work as well with Xcode 9.

`SectionInfo.plist` was renamed to `VersionedSectionInfo.plist` and the structure of the file is a bit different.
The bundle identifiers go under a `sectionInfo` key.

### CODE REVIEW

**Comment by LeoNatan** [comment]
You are on a roll! 

Thanks. This one I want to look for myself after the holidays. Will test and merge.

**Comment by erezrokah** [comment]
Thanks! I wasn't even expecting any kind of response today...

**Comment by billburgess** [comment]
Any updates on when this might get merged in?

**Comment by LeoNatan** [comment]
I will take a look at the PR very soon. Sorry it took a while.

**Pull request merged**
