### PR TITLE
Add critical alerts notification permission

### PR DESCRIPTION
**Pull request by ps2**

### CODE REVIEW

**Comment by ps2** [comment]
Closing until we find time to implement this properly, with a separate flag.

**Comment by ps2** [comment]
On second thought, this probably is useful to some as is, and shouldn't cause issues for those who don't need it, so I'll re-open it for your consideration.

**Comment by asafkorem** [comment]
Thanks for the contribution @ps2! Still relevant I guess?
In addition, I think this should be a separate flag.

**Comment by Simon-ent** [comment]
Hello, is there a work around possible until this is merged? I'm currently trying to setup Detox on a react native app that uses critical alerts and from what I understand Detox uses AppleSimulatorUtils to handle the permissions. Ideally I'm looking to use this in the following way in Detox:
`describe('Critical Alert Example', () => {
  beforeAll(async () => {
    await device.launchApp({
      permissions: {
          location: 'always',
          notifications: 'YES',
          criticalAlertSetting: 'YES',
      },
    });
  });
  }`
  Happy to help in anyway I can, although not sure what adding a separate flag would entail.

**Comment by asafkorem** [comment]
Hi @Simon-ent, shouldn't be very complicated to add this flag. You can add commits to this PR or open a new one, and if you find any complications you can contact me on Discord server ([Detox Discord](https://discord.gg/CkD5QKheF5)).
IMO we should add another flag that is enabling this feature (critical alerts) only if its value is `true` + notifications are allowed.

**Comment by asafkorem** [comment]
Thanks to @Simon-ent, we now have a better solution for this change (https://github.com/wix/AppleSimulatorUtils/pull/112). I'm closing this PR and I will make sure to mention @darinkrauss & @ps2 on the merge commit of #112 as they were the initial contributors for this.

**Pull request closed without merging**
